<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<Authors>kot23rus</Authors>
		<Company>KUBCODER</Company>
		<Description>Тесты инструментов работы с серверными файлами DAYZ SA</Description>
		<Copyright>KUBC.DAYZ.GAME.TEST Copyright (C) 2025 KUBCODER</Copyright>
		<RepositoryUrl>https://github.com/kubcoder/KUBC.DAYZ.GAME</RepositoryUrl>
		<PackageReleaseNotes>Переход на версию .NET 9</PackageReleaseNotes>
		<AssemblyName>KUBC.DAYZ.GAME.TEST</AssemblyName>
		<RootNamespace>KUBC.DAYZ.GAME</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="TestInstances\dayzOffline.enoch\**" />
	  <EmbeddedResource Remove="TestInstances\dayzOffline.enoch\**" />
	  <None Remove="TestInstances\dayzOffline.enoch\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.2" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CORE\CORE.csproj" />
	  <ProjectReference Include="..\MissionFiles\MissionFiles.csproj" />
	  <ProjectReference Include="..\Tools\Tools.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="config.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="MissionFiles\Config\Economy\Core\cfgeconomycore.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestInstances\01\db\types.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestInstances\02\cfgeconomycore.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="MissionFiles\Config\Limits\Definition\cfglimitsdefinition.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="MissionFiles\Db\Types\types.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestInstances\01\cfgeconomycore.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestInstances\02\db\maharlikaph_boats_types.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestInstances\02\db\types.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="TestInstances\02\db\types_dzn.xml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="TestInstances\01\" />
	</ItemGroup>

</Project>
