<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <Title>KUBC.DAYZ.GAME.Tools</Title>
	  <RootNamespace>KUBC.DAYZ.GAME.Tools</RootNamespace>
	  <Version>9.0.0</Version>
	  <Authors>kot23rus</Authors>
	  <Company>KUBCODER</Company>
	  <Description>Инструменты для автоматической обработки файлов конфигурации</Description>
	  <Copyright>KUBC.DAYZ.GAME.Tools Copyright (C) 2025 KUBCODER</Copyright>
	  <RepositoryUrl>https://github.com/kubcoder/KUBC.DAYZ.GAME</RepositoryUrl>
	  <PackageReleaseNotes>Добавляем обработку файлов настройки игровых предметов</PackageReleaseNotes>
	  <NeutralLanguage>ru</NeutralLanguage>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
	  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	  <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <PackageReadmeFile>Readme.md</PackageReadmeFile>
	  <PackageIcon>DayzIcon128.png</PackageIcon>
	  <PackageTags>DAYZ SA; .NET</PackageTags>
	  <PackageId>KUBC.DAYZ.GAME.Tools</PackageId>
	  <AssemblyName>KUBC.DAYZ.GAME.Tools</AssemblyName>
	  <PackageProjectUrl>https://kubcoder.ru/dayzgame/about</PackageProjectUrl>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>full</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<None Include="NOTICE.txt" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\DayzIcon128.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="Readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\MissionFiles\MissionFiles.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Resources\ItemTypes\Remover\RemoveTool.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>RemoveTool.resx</DependentUpon>
	  </Compile>
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Resources\ItemTypes\Remover\RemoveTool.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>RemoveTool.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>
</Project>
